// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
// נתחיל בלקרוא את הקלט מהשורה
        int N = Integer.parseInt(args[0]);  // כמה פעמים נריץ Math.random()

        // נספור בכמה מהמקרים המספר היה גדול מ-0.5
        int countAbove = 0;
        int countBelowOrEqual = 0;

        // לולאה שעוברת N פעמים
        int i = 0;
        while (i < N) {
            double num = Math.random();  // יוצר מספר בין 0 ל-1

            if (num > 0.5) {
                countAbove = countAbove + 1;  // נוסיף 1 אם המספר גדול מ-0.5
            } else {
                countBelowOrEqual = countBelowOrEqual + 1;  // אחרת נוסיף לצד השני
            }

            i = i + 1;  // נעלה את i באחד כל פעם
        }

        // עכשיו נדפיס את התוצאות
        System.out.println("> 0.5: " + countAbove + " times");
        System.out.println("<= 0.5: " + countBelowOrEqual + " times");

        // נחשב את היחס ביניהם (אבל רק אם countBelowOrEqual לא שווה 0)
        if (countBelowOrEqual != 0) {
            double ratio = (double) countAbove / countBelowOrEqual;
            System.out.println("Ratio: " + ratio);
        } else {
            System.out.println("Ratio: undefined (division by zero)");
        }	}
}
